### ISSUE TITLE
Control characters aren't supported

### ISSUE THREAD

**Issue by dene14** [tyleradams/json-toolkit#6]
@tyleradams First of all, thanks for a great toolset, by far this is the best opensource converter I've found across the Internet!

Seems to be a common problem for all tools (json/yaml/xml)

```
$ sed -e 's/\x01/\\u0001/g' -e 's/\x02/\\u0002/g' /path/to/valid/xml/file.xml | xml-to-json | sed -e 's/\\\\u0001/\x01/g' -e 's/\\\\u0002/\x02/g'| json-to-yaml 
Traceback (most recent call last):
  File "/usr/local/bin/json-to-yaml", line 15, in <module>
    main()
  File "/usr/local/bin/json-to-yaml", line 9, in main
    data = json.load(sys.stdin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 349 (char 348)
```

**Comment by tyleradams** [comment]
Can you verify the control character is valid JSON as per https://stackoverflow.com/questions/47607810/control-characters-in-json-string/48811496 ?

If so, this is a bug in python's core json utility, please file a bug there as well.
https://github.com/python/cpython/tree/main/Lib/json

**Comment by tyleradams** [comment]
Unlikely to be valid json
